version: 1.0.{build}
image: Visual Studio 2017
skip_tags: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
build_script:
  - dotnet build src -c Release
test:
  assemblies:
    only:
      - Miunie.Core.XUnit.Tests.dll
      - Miunie.Storage.XUnit.Tests.dll
test_script:
  - dotnet test src --test-adapter-path:. --logger:Appveyor
