//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miunie.Discord {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HelpStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Miunie.Discord.HelpStrings", typeof(HelpStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull up information about a guild..
        /// </summary>
        public static string HELP_GUILD {
            get {
                return ResourceManager.GetString("HELP_GUILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m here for you..
        /// </summary>
        public static string HELP_HELP {
            get {
                return ResourceManager.GetString("HELP_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets help for a specified command..
        /// </summary>
        public static string HELP_HELP_SEARCH {
            get {
                return ResourceManager.GetString("HELP_HELP_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give a cold-blooded negative reputation for a user....
        /// </summary>
        public static string HELP_MINUS_REP {
            get {
                return ResourceManager.GetString("HELP_MINUS_REP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give a good ol&apos; positive reputation for a user!.
        /// </summary>
        public static string HELP_PLUS_REP {
            get {
                return ResourceManager.GetString("HELP_PLUS_REP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull up a dank profile!.
        /// </summary>
        public static string HELP_PROFILE {
            get {
                return ResourceManager.GetString("HELP_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull up your current reputation log~.
        /// </summary>
        public static string HELP_REP_LOG {
            get {
                return ResourceManager.GetString("HELP_REP_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull up a reputation log for the specified user!.
        /// </summary>
        public static string HELP_REP_LOG_FOR {
            get {
                return ResourceManager.GetString("HELP_REP_LOG_FOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the official remote repository hosting the code of this bot.
        /// </summary>
        public static string HELP_REPO {
            get {
                return ResourceManager.GetString("HELP_REPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the local time for the specified user..
        /// </summary>
        public static string HELP_TIME_FOR {
            get {
                return ResourceManager.GetString("HELP_TIME_FOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the local time offset by a specified amount for a user..
        /// </summary>
        public static string HELP_TIME_FOR_OFFSET {
            get {
                return ResourceManager.GetString("HELP_TIME_FOR_OFFSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compares a user&apos;s time with your time..
        /// </summary>
        public static string HELP_TIME_GET {
            get {
                return ResourceManager.GetString("HELP_TIME_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows your local time for the specified message..
        /// </summary>
        public static string HELP_TIME_OF {
            get {
                return ResourceManager.GetString("HELP_TIME_OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set your current time offset..
        /// </summary>
        public static string HELP_TIME_SET {
            get {
                return ResourceManager.GetString("HELP_TIME_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a user&apos;s time offset..
        /// </summary>
        public static string HELP_TIME_SET_FOR {
            get {
                return ResourceManager.GetString("HELP_TIME_SET_FOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do I think? I guess you&apos;ll have to find out~.
        /// </summary>
        public static string HELP_WHAT_DO_YOU_THINK {
            get {
                return ResourceManager.GetString("HELP_WHAT_DO_YOU_THINK", resourceCulture);
            }
        }
    }
}
